on: pull_request
env:
    STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
jobs:
    build:
        name: tests-payments
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd payments && npm i && npm run test:ci
