on: pull_request

jobs:
    build:
        name: tests-tickets
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: cd tickets && npm i && npm run test:ci
