on: pull_request

jobs:
    build:
        name: tests-payments
        runs-on: ubuntu-latest
        env:
            STRIPE_KEY: ${{ secrets.STRIPE_KEY }}
        steps:
            - uses: actions/checkout@v2
            - run: cd payments && npm i && npm run test:ci
